source :rubygems

gem "rails", "3.0.9"
gem "rack"
gem "rake", "0.9.2"

gem "clearance", "~> 0.11.1"
gem "high_voltage"
gem "hoptoad_notifier", "~> 2.4.11"
gem "RedCloth", :require => "redcloth"
gem "paperclip"
gem "pg"
gem "jquery-rails"

# styles
gem "sass"
gem "flutie", "~> 1.1.8"

# forms
gem "validation_reflection"
gem "dynamic_form"
gem "formtastic"

# in :development to expose generators and rake tasks
# without having to type RAILS_ENV=test
group :development, :test do
  gem "rspec-rails", "~> 2.6.1"
end

group :test do
  gem "cucumber-rails", "0.4.1"
  gem "factory_girl_rails"
  gem "bourne"
  gem "database_cleaner"
  gem "fakeweb"
  gem "sham_rack"
  gem "timecop"
  gem "treetop"
  gem "shoulda-matchers"
  gem "launchy"
  gem "capybara-webkit"
  gem "thin"
end
